<?php
$section  = 'site_skin';
$priority = 1;

Kirki::add_field( 'tm-finance', array(
	'type'        => 'preset',
	'settings'    => 'preset',
	'description' => __( 'IMPORTANT! If you change preset, everything you have established will be gone, instead of that is the default set up of this preset.', 'tm-finance' ),
	'section'     => $section,
	'default'     => '1',
	'priority'    => $priority ++,
	'multiple'    => 3,
	'choices'     => array(
		'1' => array(
			'label'    => __( 'Preset 1', 'tm-finance' ),
			'settings' => array(
				'header_type'           => 'header01',
				'header_bg_color'       => 'rgba(255,255,255,1)',
				'logo'                  => 'http://finance.thememove.com/data/images/logo_01.png',
				'top_bg_color'          => '#F2F2F5',
				'top_text_color'        => '#666666',
				'top_link_color'        => '#666666',
				'header_padding'        => '30px 0px 30px 0px',
				'main_menu_padding'     => '22px 0px 22px 0px',
				'main_menu_color'       => '#ffffff',
				'main_menu_hover_color' => '#ffffff',
				'main_menu_margin'      => '0px 30px 0px 0px',
			),
		),
		'2' => array(
			'label'    => __( 'Preset 2', 'tm-finance' ),
			'settings' => array(
				'header_type'           => 'header02',
				'header_bg_color'       => 'rgba(255,255,255,1)',
				'logo'                  => 'http://finance.thememove.com/data/images/logo_01.png',
				'top_bg_color'          => '#F2F2F5',
				'top_text_color'        => '#666666',
				'top_link_color'        => '#666666',
				'header_padding'        => '0px 0px 0px 0px',
				'main_menu_padding'     => '40px 0px 40px 0px',
				'main_menu_color'       => '#3768B4',
				'main_menu_hover_color' => '#3768B4',
				'main_menu_margin'      => '0px 20px 0px 0px',
			),
		),
		'3' => array(
			'label'    => __( 'Preset 3', 'tm-finance' ),
			'settings' => array(
				'header_type'           => 'header03',
				'header_bg_color'       => 'rgba(255,255,255,1)',
				'logo'                  => 'http://finance.thememove.com/data/images/logo_01.png',
				'top_bg_color'          => '#F2F2F5',
				'top_text_color'        => '#666666',
				'top_link_color'        => '#666666',
				'header_padding'        => '20px 0px 20px 0px',
				'main_menu_padding'     => '22px 0px 22px 0px',
				'main_menu_color'       => '#ffffff',
				'main_menu_hover_color' => '#ffffff',
				'main_menu_margin'      => '0px 20px 0px 0px',
			),
		),
		'4' => array(
			'label'    => __( 'Preset 4', 'tm-finance' ),
			'settings' => array(
				'header_type'           => 'header04',
				'header_bg_color'       => 'rgba(255,255,255,.9)',
				'logo'                  => 'http://finance.thememove.com/data/images/logo_01.png',
				'top_bg_color'          => '#555555',
				'top_text_color'        => '#ffffff',
				'top_link_color'        => '#ffffff',
				'header_padding'        => '0px 0px 0px 0px',
				'main_menu_padding'     => '40px 0px 40px 0px',
				'main_menu_color'       => '#222222',
				'main_menu_hover_color' => '#222222',
				'main_menu_margin'      => '0px 20px 0px 0px',
			),
		),
		'5' => array(
			'label'    => __( 'Preset 5', 'tm-finance' ),
			'settings' => array(
				'header_type'           => 'header05',
				'header_bg_color'       => 'rgba(255,255,255,.9)',
				'logo'                  => 'http://finance.thememove.com/data/images/logo_04.png',
				'top_bg_color'          => '#224271',
				'top_text_color'        => '#ffffff',
				'top_link_color'        => '#ffffff',
				'header_padding'        => '0px 0px 0px 0px',
				'main_menu_padding'     => '40px 0px 40px 0px',
				'main_menu_color'       => '#ffffff',
				'main_menu_hover_color' => '#ffffff',
				'main_menu_margin'      => '0px 20px 0px 0px',
			),
		),
		'6' => array(
			'label'    => __( 'Preset 6', 'tm-finance' ),
			'settings' => array(
				'header_type'           => 'header06',
				'header_bg_color'       => 'rgba(255,255,255,.9)',
				'logo'                  => 'http://finance.thememove.com/data/images/logo_03.png',
				'top_bg_color'          => '#224271',
				'top_text_color'        => '#ffffff',
				'top_link_color'        => '#ffffff',
				'header_padding'        => '0px 0px 0px 0px',
				'main_menu_padding'     => '40px 0px 40px 0px',
				'main_menu_color'       => '#ffffff',
				'main_menu_hover_color' => '#ffffff',
				'main_menu_margin'      => '0px 20px 0px 0px',
			),
		),
	),
) );